"""administrative coordination schema: meetings, activities, communication, documents, requests, followups, escalations

Revision ID: 8db0b7b9269d
Revises: 9c8b77533035
Create Date: 2026-10-01 19:52:44.561364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db0b7b9269d'
down_revision = '9c8b77533035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # `run.sh` and the container entrypoint bootstrap with `db.create_all()`,
    # which builds every model table but never alters an existing one. On a
    # database set up that way the tables created here already exist while
    # `tasks` and `leave_requests` are still missing their new columns, so
    # every operation asks first. A database that started empty still gets the
    # full schema; nothing here is destructive.
    inspector = sa.inspect(op.get_bind())
    existing = set(inspector.get_table_names())
    created = set()

    def _create_table(*args, **kwargs):
        name = args[0]
        if name in existing:
            return
        op.create_table(*args, **kwargs)
        existing.add(name)
        created.add(name)

    def _missing_column(table, column):
        if table not in existing:
            return False
        return column not in {c['name'] for c in inspector.get_columns(table)}
    _create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('issue', sa.String(length=2000), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=True),
    sa.Column('escalate_to', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('related_type', sa.String(length=32), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=2000), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'escalations' in created:
        with op.batch_alter_table('escalations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_escalations_status'), ['status'], unique=False)

    _create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('online_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'meetings' in created:
        with op.batch_alter_table('meetings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_meetings_meeting_date'), ['meeting_date'], unique=False)

    _create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('expected_outcome', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'activities' in created:
        with op.batch_alter_table('activities', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_activities_activity_date'), ['activity_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_activities_owner_user_id'), ['owner_user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_activities_scope'), ['scope'], unique=False)

    _create_table('admin_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('resolution', sa.String(length=2000), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'admin_requests' in created:
        with op.batch_alter_table('admin_requests', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_admin_requests_requested_by'), ['requested_by'], unique=False)
            batch_op.create_index(batch_op.f('ix_admin_requests_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_admin_requests_type'), ['type'], unique=False)

    _create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'meeting_minutes' in created:
        with op.batch_alter_table('meeting_minutes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_meeting_minutes_meeting_id'), ['meeting_id'], unique=False)

    _create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=16), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'meeting_participants' in created:
        with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_meeting_participants_employee_id'), ['employee_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_meeting_participants_meeting_id'), ['meeting_id'], unique=False)

    _create_table('activity_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'activity_participants' in created:
        with op.batch_alter_table('activity_participants', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_activity_participants_activity_id'), ['activity_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_participants_employee_id'), ['employee_id'], unique=False)

    _create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'documents' in created:
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_documents_category'), ['category'], unique=False)

    _create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('minute_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['minute_id'], ['meeting_minutes.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'action_items' in created:
        with op.batch_alter_table('action_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_action_items_meeting_id'), ['meeting_id'], unique=False)

    _create_table('activity_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'activity_checklist_items' in created:
        with op.batch_alter_table('activity_checklist_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_activity_checklist_items_activity_id'), ['activity_id'], unique=False)

    _create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('presenter_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['presenter_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'agenda_items' in created:
        with op.batch_alter_table('agenda_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_agenda_items_meeting_id'), ['meeting_id'], unique=False)

    _create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('recipient_ids', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('requires_ack', sa.Boolean(), nullable=False),
    sa.Column('attachment_document_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'announcements' in created:
        with op.batch_alter_table('announcements', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_announcements_publish_date'), ['publish_date'], unique=False)

    _create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('last_action', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'followups' in created:
        with op.batch_alter_table('followups', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_followups_employee_id'), ['employee_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_followups_status'), ['status'], unique=False)

    _create_table('memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('recipient_ids', sa.Text(), nullable=True),
    sa.Column('attachment_document_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'task_comments' in created:
        with op.batch_alter_table('task_comments', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)

    _create_table('announcement_acks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'announcement_acks' in created:
        with op.batch_alter_table('announcement_acks', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_announcement_acks_announcement_id'), ['announcement_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_announcement_acks_employee_id'), ['employee_id'], unique=False)

    if _missing_column('leave_requests', 'note'):
        with op.batch_alter_table('leave_requests', schema=None) as batch_op:
            batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))

    task_columns = {
        'submitted_date': sa.Column('submitted_date', sa.DateTime(timezone=True), nullable=True),
        'attachments': sa.Column('attachments', sa.Text(), nullable=True),
        'meeting_id': sa.Column('meeting_id', sa.Integer(), nullable=True),
        'activity_id': sa.Column('activity_id', sa.Integer(), nullable=True),
    }
    missing_task_columns = [name for name in task_columns
                            if _missing_column('tasks', name)]
    if missing_task_columns:
        with op.batch_alter_table('tasks', schema=None) as batch_op:
            for name in missing_task_columns:
                batch_op.add_column(task_columns[name])
            if 'meeting_id' in missing_task_columns:
                batch_op.create_foreign_key('fk_tasks_meeting_id', 'meetings', ['meeting_id'], ['id'])
            if 'activity_id' in missing_task_columns:
                batch_op.create_foreign_key('fk_tasks_activity_id', 'activities', ['activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    existing = set(inspector.get_table_names())

    def _drop_table(name):
        if name not in existing:
            return
        op.drop_table(name)
        existing.discard(name)

    def _has_column(table, column):
        if table not in existing:
            return False
        return column in {c['name'] for c in inspector.get_columns(table)}

    def _fk_exists(table, name):
        if table not in existing:
            return False
        return any(fk.get('name') == name for fk in inspector.get_foreign_keys(table))
    if _has_column('tasks', 'submitted_date'):
        drop_fks = [fk for fk in ('fk_tasks_activity_id', 'fk_tasks_meeting_id')
                    if _fk_exists('tasks', fk)]
        with op.batch_alter_table('tasks', schema=None) as batch_op:
            for fk in drop_fks:
                batch_op.drop_constraint(fk, type_='foreignkey')
            for column in ('activity_id', 'meeting_id', 'attachments', 'submitted_date'):
                if _has_column('tasks', column):
                    batch_op.drop_column(column)

    if _has_column('leave_requests', 'note'):
        with op.batch_alter_table('leave_requests', schema=None) as batch_op:
            batch_op.drop_column('note')

    if 'announcement_acks' in existing:
        with op.batch_alter_table('announcement_acks', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_announcement_acks_employee_id'))
            batch_op.drop_index(batch_op.f('ix_announcement_acks_announcement_id'))

    _drop_table('announcement_acks')
    if 'task_comments' in existing:
        with op.batch_alter_table('task_comments', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))

    _drop_table('task_comments')
    _drop_table('memos')
    if 'followups' in existing:
        with op.batch_alter_table('followups', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_followups_status'))
            batch_op.drop_index(batch_op.f('ix_followups_employee_id'))

    _drop_table('followups')
    if 'announcements' in existing:
        with op.batch_alter_table('announcements', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_announcements_publish_date'))

    _drop_table('announcements')
    if 'agenda_items' in existing:
        with op.batch_alter_table('agenda_items', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_agenda_items_meeting_id'))

    _drop_table('agenda_items')
    if 'activity_checklist_items' in existing:
        with op.batch_alter_table('activity_checklist_items', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_activity_checklist_items_activity_id'))

    _drop_table('activity_checklist_items')
    if 'action_items' in existing:
        with op.batch_alter_table('action_items', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_action_items_meeting_id'))

    _drop_table('action_items')
    if 'documents' in existing:
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_documents_category'))

    _drop_table('documents')
    if 'activity_participants' in existing:
        with op.batch_alter_table('activity_participants', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_activity_participants_employee_id'))
            batch_op.drop_index(batch_op.f('ix_activity_participants_activity_id'))

    _drop_table('activity_participants')
    if 'meeting_participants' in existing:
        with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_meeting_participants_meeting_id'))
            batch_op.drop_index(batch_op.f('ix_meeting_participants_employee_id'))

    _drop_table('meeting_participants')
    if 'meeting_minutes' in existing:
        with op.batch_alter_table('meeting_minutes', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_meeting_minutes_meeting_id'))

    _drop_table('meeting_minutes')
    if 'admin_requests' in existing:
        with op.batch_alter_table('admin_requests', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_admin_requests_type'))
            batch_op.drop_index(batch_op.f('ix_admin_requests_status'))
            batch_op.drop_index(batch_op.f('ix_admin_requests_requested_by'))

    _drop_table('admin_requests')
    if 'activities' in existing:
        with op.batch_alter_table('activities', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_activities_scope'))
            batch_op.drop_index(batch_op.f('ix_activities_owner_user_id'))
            batch_op.drop_index(batch_op.f('ix_activities_activity_date'))

    _drop_table('activities')
    if 'meetings' in existing:
        with op.batch_alter_table('meetings', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_meetings_meeting_date'))

    _drop_table('meetings')
    if 'escalations' in existing:
        with op.batch_alter_table('escalations', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_escalations_status'))

    _drop_table('escalations')
    # ### end Alembic commands ###
