"""empty message

Revision ID: 24ee4979f95f
Revises: abc123def456
Create Date: 2026-06-29 17:36:05.503721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ee4979f95f'
down_revision = 'abc123def456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_payment_reminder_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_reminder_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('payment_reminder_count')
        batch_op.drop_column('last_payment_reminder_sent')

    # ### end Alembic commands ###
