"""Initial migration: current model state with grading tables

Revision ID: 4a0ca455098d
Revises: 
Create Date: 2026-06-08 18:18:35.399006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a0ca455098d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop in order that respects foreign key dependencies
    op.drop_table('user_answer')
    op.drop_table('user_badge')  # Must drop before badge (FK dependency)
    op.drop_table('badge')
    op.drop_table('quiz_attempt')
    op.drop_table('lesson_completion')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('announcements_cohort_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'application_windows', ['cohort_id'], ['id'])

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('course_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_profile_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('has_used_tool', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tool_skill_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tool_tasks_done', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skill_open_answer', sa.Text(), nullable=True))
        batch_op.alter_column('last_payment_reminder_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('enrollment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
        batch_op.alter_column('payment_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'full'::character varying"))
        batch_op.alter_column('payment_methods',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('require_payment_before_application',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('paypal_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('mobile_money_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('bank_transfer_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('kpay_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('bank_transfer_details',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('installment_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('payment_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('cohort_start_notified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint(batch_op.f('_student_course_uc'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_enrollments_course'))
        batch_op.drop_index(batch_op.f('idx_enrollments_student'))
        batch_op.create_unique_constraint('_student_course_cohort_uc', ['student_id', 'course_id', 'application_window_id'])
        batch_op.drop_column('payment_reminder_sent_at')
        batch_op.drop_column('payment_reminder_sent')

    with op.batch_alter_table('forum_post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_forum_post_likes_user_post'))
        batch_op.create_unique_constraint('_post_user_like_uc', ['post_id', 'user_id'])

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_forum_posts_author_id'))
        batch_op.drop_index(batch_op.f('idx_forum_posts_created_at'))
        batch_op.drop_index(batch_op.f('idx_forum_posts_forum_id'))
        batch_op.drop_index(batch_op.f('idx_forum_posts_is_active'))
        batch_op.drop_index(batch_op.f('idx_forum_posts_is_approved'))
        batch_op.drop_index(batch_op.f('idx_forum_posts_is_flagged'))
        batch_op.drop_index(batch_op.f('idx_forum_posts_parent_id'))
        batch_op.create_foreign_key(None, 'users', ['moderated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['edited_by'], ['id'])
        batch_op.drop_column('reply_count')
        batch_op.drop_column('edit_count')
        batch_op.drop_column('last_edited_by')
        batch_op.drop_column('last_edited_at')

    with op.batch_alter_table('forum_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_forum_subscriptions_user_forum'))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lessons_module'))

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_modules_course'))

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_quiz_attempts_quiz'))
        batch_op.drop_index(batch_op.f('idx_quiz_attempts_user'))

    with op.batch_alter_table('student_forums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_student_forums_category'))
        batch_op.drop_index(batch_op.f('idx_student_forums_course_id'))
        batch_op.drop_index(batch_op.f('idx_student_forums_is_active'))
        batch_op.drop_column('subscriber_count')
        batch_op.drop_column('last_post_at')
        batch_op.drop_column('post_count')
        batch_op.drop_column('thread_count')
        batch_op.drop_column('last_post_id')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submissions_student'))

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_achievements_achievement'))
        batch_op.drop_index(batch_op.f('idx_user_achievements_user'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_constraint(batch_op.f('users_email_unsubscribe_token_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_email_unsubscribe_token_key'), ['email_unsubscribe_token'])
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_achievements_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_achievements_achievement'), ['achievement_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_submissions_student'), ['student_id'], unique=False)

    with op.batch_alter_table('student_forums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_post_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thread_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_post_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscriber_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_student_forums_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_student_forums_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_student_forums_category'), ['category'], unique=False)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_quiz_attempts_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_quiz_attempts_quiz'), ['quiz_id'], unique=False)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_modules_course'), ['course_id'], unique=False)

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lessons_module'), ['module_id'], unique=False)

    with op.batch_alter_table('forum_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_forum_subscriptions_user_forum'), ['user_id', 'forum_id'], unique=False)

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_edited_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('edit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reply_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_forum_posts_parent_id'), ['parent_post_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_forum_posts_is_flagged'), ['is_flagged'], unique=False)
        batch_op.create_index(batch_op.f('idx_forum_posts_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('idx_forum_posts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_forum_posts_forum_id'), ['forum_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_forum_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_forum_posts_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('forum_post_likes', schema=None) as batch_op:
        batch_op.drop_constraint('_post_user_like_uc', type_='unique')
        batch_op.create_index(batch_op.f('idx_forum_post_likes_user_post'), ['user_id', 'post_id'], unique=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reminder_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_reminder_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('_student_course_cohort_uc', type_='unique')
        batch_op.create_index(batch_op.f('idx_enrollments_student'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_enrollments_course'), ['course_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('_student_course_uc'), ['student_id', 'course_id'])
        batch_op.alter_column('cohort_start_notified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('payment_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('installment_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('bank_transfer_details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('kpay_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('bank_transfer_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('mobile_money_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('paypal_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('require_payment_before_application',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('payment_methods',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('payment_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'full'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
        batch_op.alter_column('enrollment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))

    with op.batch_alter_table('course_applications', schema=None) as batch_op:
        batch_op.alter_column('is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('last_payment_reminder_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('skill_open_answer')
        batch_op.drop_column('tool_tasks_done')
        batch_op.drop_column('tool_skill_level')
        batch_op.drop_column('has_used_tool')
        batch_op.drop_column('skill_profile_key')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('announcements_cohort_id_fkey'), 'application_windows', ['cohort_id'], ['id'], ondelete='SET NULL')

    # Create tables in dependency order: badge before user_badge
    op.create_table('badge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('criteria_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('badge_pkey')),
    sa.UniqueConstraint('name', name=op.f('badge_name_key'))
    )
    op.create_table('user_badge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('context_course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], name=op.f('user_badge_badge_id_fkey')),
    sa.ForeignKeyConstraint(['context_course_id'], ['courses.id'], name=op.f('user_badge_context_course_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_badge_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_badge_pkey')),
    sa.UniqueConstraint('user_id', 'badge_id', 'context_course_id', name=op.f('uq_user_badge_context'))
    )
    op.create_table('lesson_completion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_completion_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lesson_completion_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_completion_pkey')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('uq_user_lesson_completion'))
    )
    op.create_table('quiz_attempt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=22), autoincrement=False, nullable=False),
    sa.Column('feedback_viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_attempt_quiz_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_attempt_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_attempt_pkey'))
    )
    op.create_table('user_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('points_awarded', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('instructor_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('user_answer_question_id_fkey')),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempt.id'], name=op.f('user_answer_quiz_attempt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_answer_pkey'))
    )
    # ### end Alembic commands ###
