"""add rubric_id to assignments and projects

Revision ID: abc123def456
Revises: 5581c97b79fe
Create Date: 2026-06-28 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = '5581c97b79fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_assignment_rubric', 'rubrics', ['rubric_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_project_rubric', 'rubrics', ['rubric_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_rubric', type_='foreignkey')
        batch_op.drop_column('rubric_id')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignment_rubric', type_='foreignkey')
        batch_op.drop_column('rubric_id')
    # ### end Alembic commands ###
