"""Align system_settings.key uniqueness and drop the legacy projects.tasks column.

Revision ID: c6a713393185
Revises: c7f1a2b3c4d5
Create Date: 2026-08-11 09:36:51.747668

NOTE: this migration was hand-adjusted from the autogenerated output:
  * Removed the rubric_data JSONB -> JSON type change (the DB column is
    intentionally JSONB; changing it adds risk for zero benefit).
  * system_settings: deduplicates rows before creating the UNIQUE(key)
    constraint (two full default sets were seeded at different times), and
    names the constraint to match the model's `unique=True` convention.
  * projects.tasks is dropped because the model no longer declares it and
    the table is empty.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c6a713393185'
down_revision = 'c7f1a2b3c4d5'
branch_labels = None
depends_on = None


def _inspector():
    """Fresh inspector per call (Inspector caches reflection per instance)."""
    return sa.inspect(op.get_bind())


def upgrade():
    bind = op.get_bind()

    # ─────────────────────────────────────────────────────────────────────
    # system_settings – deduplicate, then add UNIQUE(key).
    #
    # History: two complete default settings sets were seeded at different
    # dates (ids 1-35 twice), so every key currently has 2 rows and there is
    # no primary key on the table. Keep the most recently updated row per
    # key, then enforce uniqueness to match the model (key unique=True).
    # ─────────────────────────────────────────────────────────────────────
    if _inspector().has_table('system_settings'):
        bind.execute(sa.text(
            """
            DELETE FROM system_settings
            WHERE updated_at IS NULL
               OR updated_at < (
                   SELECT max(updated_at)
                   FROM system_settings AS keep
                   WHERE keep.key = system_settings.key
               )
            """
        ))

        # Safety net: if duplicates remain (e.g. two rows share the same
        # updated_at), fail loudly instead of crashing on the constraint.
        remaining = bind.execute(sa.text(
            """
            SELECT count(*) FROM (
                SELECT key FROM system_settings GROUP BY key HAVING count(*) > 1
            ) AS dup
            """
        )).scalar()
        if remaining:
            raise RuntimeError(
                f"system_settings still has {remaining} duplicated key(s) after dedup; "
                "manual cleanup required before the unique constraint can be added"
            )

        existing_uq = {
            tuple(c['column_names'] or [])
            for c in _inspector().get_unique_constraints('system_settings')
        }
        if ('key',) not in existing_uq:
            with op.batch_alter_table('system_settings', schema=None) as batch_op:
                batch_op.create_unique_constraint('system_settings_key_key', ['key'])

    # ─────────────────────────────────────────────────────────────────────
    # projects – drop the legacy `tasks` column.
    #
    # The Project model no longer declares it (autogenerate reported it as
    # "removed column"), and the projects table is empty, so no data is
    # lost. The get_tasks()/set_tasks() helpers are legacy no-ops.
    # ─────────────────────────────────────────────────────────────────────
    if _inspector().has_table('projects'):
        existing_cols = {c['name'] for c in _inspector().get_columns('projects')}
        if 'tasks' in existing_cols:
            with op.batch_alter_table('projects', schema=None) as batch_op:
                batch_op.drop_column('tasks')


def downgrade():
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint('system_settings_key_key', type_='unique')
