"""empty message

Revision ID: d0a3470a3262
Revises: 8a76457630cf
Create Date: 2026-06-19 20:00:49.264413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a3470a3262'
down_revision = '8a76457630cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_verification_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_enrollments_payment_verification_hash'), ['payment_verification_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_payment_verification_hash'))
        batch_op.drop_column('payment_verification_hash')

    # ### end Alembic commands ###
