"""add community_link to application_windows

Revision ID: e2d44041ddf2
Revises: 4a0ca455098d
Create Date: 2026-06-11 19:41:01.883990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d44041ddf2'
down_revision = '4a0ca455098d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_windows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('community_link_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_windows', schema=None) as batch_op:
        batch_op.drop_column('community_link_label')
        batch_op.drop_column('community_link')

    # ### end Alembic commands ###
